import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Navigation, { NavLink } from "~/components/navigation/Navigation";

const inter = Inter({ subsets: ["latin"] });

const NAVIGATION_LINKS: NavLink[] = [
  { href: "/", label: "Home" },
  {
    label: "Services",
    sublinks: [
      { href: "/services/development", label: "Development" },
      { href: "/services/design", label: "Design" },
      { href: "/services/consulting", label: "Consulting" },
    ],
  },
  { href: "/about", label: "About" },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full w-full">
        <Navigation links={NAVIGATION_LINKS} />

        <div className="my-40">more 1 </div>
        <div className="my-40">more 2 </div>
        <div className="my-40">more 3 </div>
        <div className="my-40">more 4 </div>
        <div className="my-40">more 5 </div>
        <div className="my-40">more 6 </div>
        <div className="my-40">more 7 </div>
        <div className="my-40">more 8 </div>
      </main>
    </>
  );
}
